language: python

python:
  - 3.5
  - 3.6

install:
    - pip install scrutinizer-ocular
    - travis_retry pip install coverage
before_script:
  - ./setup.py install

script:
  - coverage3 run run_tests.py

after_script:
  - ocular --data-file ".coverage"

